apiVersion: v1
kind: Service
metadata:
  name: scb-frontend-newui
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: 80
  selector:
    app: scb-frontend-newui
    release: v1